version: '3.8'

services:
  filmios-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: filmios-backend
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - .:/application
    environment:
      DB_CONNECTION: pgsql
    networks:
      - filmios-network

  # filmios-frontend:
  #   image: node
  #   container_name: filmios-frontend
  #   working_dir: /filmios-frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - $HOME/.ssh:/root/.ssh
  #     - $HOME/project/filmios-frontend:/filmios-frontend
  #   command: ["npm", "run", "dev", "--", "--host"]
  #   networks:
  #     - filmios-network

  db-filmios:
    image: postgres
    container_name: db-filmios
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - filmios-network

networks:
  filmios-network:
    driver: bridge
